### ISSUE TITLE
Cấu hình hiển thị

### ISSUE THREAD

**Issue by hpleduit** [hoaquynhtim99/work-schedules#1]
hông báo từ Hệ thống Nên chú ý   Nên chú ý: Undefined index: display_element in file /modules/work-schedules/admin/config-display.php on line 56
Nên chú ý    Nên chú ý: Undefined index: require_element in file /modules/work-schedules/admin/config-display.php on line 57
Nên chú ý    Nên chú ý: Undefined index: require_element in file /modules/work-schedules/admin/config-display.php on line 58 

**Ngoài trang chủ nếu tích hợp tính năng in lịch và tải lịch nữa là OK. Cảm ơn nhiều**

**Comment by hoaquynhtim99** [comment]
Chào bạn, bản của bạn tải là bản đang phát triển (chưa xong) nên có các thông báo đó, bạn tải lại module chính thức ở đây https://github.com/hoaquynhtim99/work-schedules/releases

**Comment by hpleduit** [comment]
Thanks bạn mình đã test ok còn vấn đề này nữa khi không đăng nhập kích chọn Đăng ký lịch mới chuyển sang trang thông báo kích để đăng nhập thì kích vào link để tải form đăng nhập thì thông báo lỗi này javascript:loginForm(); trả về giá trị false. Tại sao không hiện thị được form đăng nhập. Bạn kiểm tra lại nhé. 
Chức năng In và tải lịch vẫn chưa hoàn thành hả bạn.
Cảm ơn bạn đã đóng góp nhiệt tình cho ngành giáo dục.

**Comment by hoaquynhtim99** [comment]
> javascript:loginForm();

Cái này bạn phải kiểm tra lại giao diện mình đang dùng bắt buộc phải có  hàm javascript đó nhé, đối chiếu với file themes/default/js/main.js

**Comment by khucthuydu** [comment]
> Thanks bạn mình đã test ok còn vấn đề này nữa khi không đăng nhập kích chọn Đăng ký lịch mới chuyển sang trang thông báo kích để đăng nhập thì kích vào link để tải form đăng nhập thì thông báo lỗi này javascript:loginForm(); trả về giá trị false. Tại sao không hiện thị được form đăng nhập. Bạn kiểm tra lại nhé. 
> Chức năng In và tải lịch vẫn chưa hoàn thành hả bạn.
> Cảm ơn bạn đã đóng góp nhiệt tình cho ngành giáo dục.
> 

Mình cũng bị lỗi tương tự khi chạy trên Firefox, nhưng chạy bằng chrome hay opera thì bình thường!
