### ISSUE TITLE
Lỗi tính số tuần trong năm

### ISSUE THREAD

**Issue by mathagu** [hoaquynhtim99/work-schedules#3]
Thuật toán tính số thứ tự của tuần hiện hành chưa phù hợp vì tính tuần và năm không đi cùng với nhau.

Theo quy ước trong module thì một tuần bắt đầu từ thứ Hai, kết thúc là Chủ nhật, tuần chứa ngày 1/1 năm nào sẽ là tuần thứ nhất của năm đó.

Như vậy, ngày 26/12/2016 sẽ phải nằm ở tuần thứ nhất của năm 2017 $week = 1, $year = 2017. Nhưng lệnh các lệnh $week = nv_get_week_from_time(NV_CURRENTTIME); $year = date('Y'); sẽ cho ra kết quả là $week = 1, $year = 2016.

**Comment by mathagu** [comment]
Ngoài ra, nếu theo quy ước như trên thì năm 2017 sẽ có 53 tuần, chứ không phải là 52, nên khi xem lịch ở năm 2017 sẽ bị như trong ảnh (sau tuần thứ 52 của năm 2017 là tuần thứ 1 với ngày bắt đầu là 25/12, ngày kết thúc là 31/12) .
![image](https://cloud.githubusercontent.com/assets/11552661/21487728/f1f9e602-cc03-11e6-98ac-50675fa41a85.png)

**Comment by hoaquynhtim99** [comment]
Cảm ơn bạn vì một phân tích rất chi tiết, mình đã sửa lỗi và bạn có thể cập nhật từ admin control panel.

**Comment by mathagu** [comment]
Khi phát hiện lỗi này thì mình cũng đã mày mò để chỉnh sửa lại, về cơ bản cũng gần như những cái bạn đã chỉnh sửa! Chỉ có hàm tính tổng số tuần của năm thì mình làm chưa tốt lắm, sẽ học hỏi thêm ở hàm của bạn! :D
