### ISSUE TITLE
Đề xuất làm thêm phần trình chiếu sang tivi LCD 

### ISSUE THREAD

**Issue by binhminhs11** [hoaquynhtim99/work-schedules#4]
work-schedules này làm thêm phần giao diện trình chiếu lịch sang Tivi LCD nữa làm thật ok luôn

**Comment by hoaquynhtim99** [comment]
@binhminhs11 Mình đọc cái này không hiểu gì cả

**Comment by binhminhs11** [comment]
https://www.youtube.com/watch?v=95aNd4rpQ_E

làm thêm phần giao diện trình chiếu lịch sang Tivi LCD giống như trên. Hiện nay các cơ quan nhà nước làm như vậy nhiều !

**Comment by hoaquynhtim99** [comment]
Mình xin đóng issue này lại nhé, nếu ngày nào đó có nhà hảo tâm nào đó tài trợ có lẽ module này sẽ có chức năng đó.
